# Generated by Django 4.2 on 2023-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_equipped_classrooms', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Специально оборудованные учебные кабинеты')),
                ('practical_training_facilities', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Объекты для проведения практических занятий')),
                ('libraries', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Библиотеки')),
                ('sports_facilities', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Объекты спорта')),
                ('educational_resources', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Средства обучения и воспитания')),
                ('accessible_buildings', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Беспрепятственный доступ в здания образовательной организации')),
                ('special_dietary_requirements', models.TextField(blank=True, null=True, verbose_name='Специальные условия питания')),
                ('electronic_resources_accessibility', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Доступность электронных образовательных ресурсов')),
                ('special_technical_learning_tools', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Специальные технические средства обучения')),
                ('dormitory_accessible_conditions', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Условия беспрепятственного доступа в общежитие')),
                ('adapted_housing_units_in_dormitory', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество жилых помещений для инвалидов в общежитии')),
            ],
            options={
                'verbose_name': 'Доступная среда',
            },
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreements', models.TextField(blank=True, null=True, verbose_name='Заключенные и планируемые договоры')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Документ')),
                ('accreditation', models.TextField(blank=True, null=True, verbose_name='Международная аккредитация образовательных программ')),
                ('document2', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Международное сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='VacantSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Реализуемая образовательная программа')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Реализуемая специальность')),
                ('training_direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Реализуемое направление подготовки')),
                ('scientific_specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Научная специальность')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Реализуемая профессия')),
                ('federal_budget_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество вакантных мест за счёт бюджетных ассигнований федерального бюджета')),
                ('regional_budget_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество вакантных мест за счёт бюджетных ассигнований бюджетов субъекта Российской Федерации')),
                ('local_budget_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество вакантных мест за счёт бюджетных ассигнований местных бюджетов')),
                ('private_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество вакантных мест за счёт средств физических и (или) юридических лиц')),
            ],
            options={
                'verbose_name': 'Вакантное место',
                'verbose_name_plural': 'Вакантные места',
            },
        ),
    ]
