# Generated by Django 4.2 on 2023-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDocs', models.CharField(max_length=300, verbose_name='Название документа')),
                ('docs', models.FileField(blank=True, default=None, null=True, upload_to='docs', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, default='static/gerb.png', upload_to='news_images', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOtdel', models.CharField(max_length=128, unique=True, verbose_name='Название отдела ')),
                ('nameRab', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('nameSon', models.CharField(max_length=128, verbose_name='Отчество')),
                ('dolg', models.CharField(max_length=128, verbose_name='Должность')),
                ('biograf', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Структура организации',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
