# Generated by Django 4.2 on 2023-06-18 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_document_docs_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
        migrations.AddField(
            model_name='document',
            name='dateDocs',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
