# Generated by Django 4.2 on 2023-06-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdel',
            name='docsOtdel',
            field=models.FileField(blank=True, help_text='Необязательное поле. Вы можете оставить его пустым.', null=True, upload_to='static/docs', verbose_name='Положения'),
        ),
    ]
