# Generated by Django 4.2 on 2023-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_otdel_docsotdel'),
    ]

    operations = [
        migrations.CreateModel(
            name='elementsObraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formObuch', models.CharField(max_length=200, verbose_name='Форма обучения')),
                ('normSrokObuch', models.TextField(blank=True, null=True, verbose_name='Нормативный срок обучения')),
                ('srokAkreditObuch', models.TextField(blank=True, null=True, verbose_name='Срок действия гос. аккредитации образовательной программы ')),
                ('languageObraz', models.CharField(max_length=200, verbose_name='Языки, на которых осуществляется образовательная программа')),
                ('moduleObraz', models.TextField(blank=True, null=True, verbose_name='учебные курсы, предусмотренные соответствующей образовательной программы')),
                ('praktikObraz', models.TextField(blank=True, null=True, verbose_name='Практики, предусмотренные соответствующей образовательной программы')),
                ('distanceObraz', models.TextField(blank=True, null=True, verbose_name='образовательной программы при реализации элек. обучения на дистанционном обучении')),
                ('uchebPlan', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name="Учебный план образовательной программы'электронный документ'")),
                ('annatotionDis', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='об аннотации по рабочим программам')),
                ('calendarUcheb', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Календарный учебный график')),
                ('metodDocs', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='о методических документах образ. процесса ')),
                ('obshislo', models.CharField(max_length=100, verbose_name='Общая численность обучающихся')),
                ('obshisloBudgetFed', models.CharField(max_length=100, verbose_name='Общая численность обучающихся за счет федеральных бюджетных средств')),
                ('obshisloBudgetReg', models.CharField(max_length=100, verbose_name='Общая численность обучающихся за счет бюджетных средств субъекта')),
                ('obshisloBudgetSMO', models.CharField(max_length=100, verbose_name='Общая численность обучающихся за счет местных бюджетов')),
                ('obshisloDogovor', models.CharField(max_length=100, verbose_name='Общая численность обучающихся по договору об образовании')),
            ],
        ),
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameObraz', models.CharField(max_length=200, verbose_name='Название образовательной программы ')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
    ]
