# Generated by Django 4.2 on 2023-07-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_elementsobraz_nameobr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementsobraz',
            options={'verbose_name': 'Об образовательной программе', 'verbose_name_plural': 'Об образовательных программах'},
        ),
    ]
