# Generated by Django 4.2 on 2023-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_elementsobraz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsobraz',
            name='Licenzy',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Лицензия на осуществление образовательной деятельности'),
        ),
    ]
