# Generated by Django 4.2 on 2023-07-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FedStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimenObrStandart', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='О применяемых государственных образовательных стандартах')),
                ('PrimenObrStandartText', models.TextField(blank=True, null=True, verbose_name='Описание применяемых государственных образовательные стандарты')),
                ('UtverObrStandart', models.FileField(blank=True, default=None, null=True, upload_to='static/docs', verbose_name='Об утвержденных государственных стандартах')),
                ('UtverObrStandartText', models.TextField(blank=True, null=True, verbose_name='Описание утвержденных государственных стандартах')),
            ],
            options={
                'verbose_name': 'Об образовательных стандарте и требованиях',
                'verbose_name_plural': 'Об образовательных стандарте и требованиях',
            },
        ),
        migrations.CreateModel(
            name='PedagogicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'информация об отделе',
                'verbose_name_plural': 'информация о отделах',
            },
        ),
        migrations.CreateModel(
            name='EducationalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('education_level', models.CharField(max_length=255, verbose_name='Уровень образования')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('training_direction', models.CharField(max_length=255, verbose_name='Направление обучения')),
                ('scientific_degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Научная степень')),
                ('academic_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание')),
                ('training_experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опыт педагогической работы')),
                ('work_experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Общий стаж работы')),
                ('subjects_taught', models.TextField(verbose_name='Преподаваемые предметы')),
                ('pedagogical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.pedagogicalstaff', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'педагогических работниках, реализующих каждую образовательную программу',
                'verbose_name_plural': 'педагогических работниках, реализующих каждую образовательную программу',
            },
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('pedagogical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.pedagogicalstaff', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'заместителе руководителя образовательной организации. ',
                'verbose_name_plural': 'заместителе руководителя образовательной организации. ',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('pedagogical_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.pedagogicalstaff', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'руководителях филиалов или представительств образовательной организации',
                'verbose_name_plural': 'руководителях филиалов или представительств образовательной организации',
            },
        ),
    ]
