# Generated by Django 4.2 on 2023-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedagogicalstaff',
            name='first_name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
